### ISSUE TITLE
pure cpu works but cublas doesnt

### ISSUE THREAD

**Issue by hiqsociety** [go-skynet/go-llama.cpp#219]
```
CGO_LDFLAGS="-lcublas -lcudart -L/usr/local/cuda/lib64/" LIBRARY_PATH=$PWD C_INCLUDE_PATH=$PWD ./main -m ../llama.cpp/models/llama-2-7b-32k-instruct.Q6_K.gguf -t 1
create_gpt_params: loading model ../llama.cpp/models/llama-2-7b-32k-instruct.Q6_K.gguf
SIGSEGV: segmentation violation
PC=0x7efd0294bfbd m=0 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x49f6e0, 0xc00005ca90)
	/usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc00005ca68 sp=0xc00005ca30 pc=0x41522b
github.com/go-skynet/go-llama%2ecpp._Cfunc_load_model(0xf71100, 0x80, 0x0, 0x1, 0x0, 0x1, 0x1, 0x0, 0x0, 0x200, ...)
	_cgo_gotypes.go:267 +0x4f fp=0xc00005ca90 sp=0xc00005ca68 pc=0x49c04f
github.com/go-skynet/go-llama%2ecpp.New({0x7ffd1cb3567b, 0x35}, {0xc00005ce20, 0x4, 0x1?})
	/usr/local/src/go-llama.cpp/llama.go:39 +0x385 fp=0xc00005cca0 sp=0xc00005ca90 pc=0x49c7a5
main.main()
	/usr/local/src/go-llama.cpp/examples/main.go:37 +0x3bd fp=0xc00005cf40 sp=0xc00005cca0 pc=0x49e93d
runtime.main()
	/usr/local/go/src/runtime/proc.go:267 +0x2bb fp=0xc00005cfe0 sp=0xc00005cf40 pc=0x445c9b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0x46fd21

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00004cfa8 sp=0xc00004cf88 pc=0x4460ee
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:322 +0xb3 fp=0xc00004cfe0 sp=0xc00004cfa8 pc=0x445f73
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00004cfe8 sp=0xc00004cfe0 pc=0x46fd21
created by runtime.init.6 in goroutine 1
	/usr/local/go/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00004d778 sp=0xc00004d758 pc=0x4460ee
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:280 +0x94 fp=0xc00004d7c8 sp=0xc00004d778 pc=0x432a14
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:200 +0x25 fp=0xc00004d7e0 sp=0xc00004d7c8 pc=0x427da5
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00004d7e8 sp=0xc00004d7e0 pc=0x46fd21
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000076000?, 0x59f718?, 0x1?, 0x0?, 0xc0000071e0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc00004df70 sp=0xc00004df50 pc=0x4460ee
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0xa26d40)
	/usr/local/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc00004dfa0 sp=0xc00004df70 pc=0x4302a9
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:653 +0x3c fp=0xc00004dfc8 sp=0xc00004dfa0 pc=0x43083c
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:201 +0x25 fp=0xc00004dfe0 sp=0xc00004dfc8 pc=0x427d45
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00004dfe8 sp=0xc00004dfe0 pc=0x46fd21
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:201 +0xa5

goroutine 18 [finalizer wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000048628 sp=0xc000048608 pc=0x4460ee
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000487e0 sp=0xc000048628 pc=0x426e27
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000487e8 sp=0xc0000487e0 pc=0x46fd21
created by runtime.createfing in goroutine 1
	/usr/local/go/src/runtime/mfinal.go:163 +0x3d

rax    0x0
rbx    0xf719a8
rcx    0x7efcf8619c80
rdx    0x0
rdi    0xf719a8
rsi    0x7ffd1cb33d40
rbp    0x7ffd1cb33d40
rsp    0x7ffd1cb33a20
r8     0x57
r9     0xf71be0
r10    0x7efd0280d258
r11    0x7efcf8619ce0
r12    0x0
r13    0x0
r14    0xf719b8
r15    0x7ffd1cb33d20
rip    0x7efd0294bfbd
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by hiqsociety** [comment]
@MathiasGS any help in this?

**Comment by mudler** [comment]
dup of https://github.com/go-skynet/go-llama.cpp/issues/218
